### ISSUE TITLE
Minimum node version requirement

### ISSUE THREAD

**Issue by emptyshells** [styfle/og-image#50]
Is there a minimum node version requirement that should be added to the package.json to specify which versions of node this works with?  Would it be a good idea to support the newest LTS version of Node or the oldest, or even older versions than that?

Could we get a CI build integrated with the repo to test this?

For instance

```json
{
  "engines": {
    "node": "10.15.1",
    "npm": "6.4.1"
  }
}
```

**Comment by styfle** [comment]
Hi Brian,

This repo uses [Now GitHub integration](https://zeit.co/github) which builds each PR (just like CI) and displays results.

You can even see which build failed, the frontend (package.json static build) or the backend (card.ts lambda build) in the case of this repo.

![image](https://user-images.githubusercontent.com/229881/52440315-be4e6280-2aeb-11e9-828b-48ee92de8d8c.png)

You can use the latest Node LTS for development.
Node 10.x or Node 8.x should work fine.

**Comment by emptyshells** [comment]
Just noticed that when opening my PR.  Thanks Steven.  Had no idea what Now was up until I opened that PR.  😄
